### ISSUE TITLE
Fails to build on OpenBSD 6.5

### ISSUE THREAD

**Issue by SenorAgosto** [comby-tools/comby#117] opened 2019-10-02 04:24 UTC
**Describe the bug**
This is not a bug with Comby per se, but I am having trouble building it on OpenBSD 6.5 because it cannot find <pcre.h> which lives here: `/usr/local/include/pcre.h`. 

The build fails on the `opam install -y pcre` step.

I know nothing about OCaml, so I'm at a loss as to how to add include paths, `opam` doesn't seem to be looking in `/usr/local/include`? 

**Reproducing**
Follow README build instructions on OpenBSD 6.5.

**Expected behavior**
With the correct dependency installed, I would expect the build to successfully complete. 

**Additional context**
Here is the full error. 

![opam_pcre](https://user-images.githubusercontent.com/250468/66017922-85ac3080-e4a2-11e9-98bf-f812546d0540.png)

Any help would be much appreciated.

**Comment by rvantonder** [comment] 2019-10-02 04:35
Ah, looks like you need the `pcre` system dependency first (similar to installing the OS dependencies using `apt-get`: `sudo apt-get install libpcre3-dev` or similar). I'm not totally sure what this is for BSD, but it looks like it's `sudo pkg_add -v pcre`. Try that, and then try the `opam install` command again?

**Comment by rvantonder** [comment] 2019-10-02 04:37
Hmm, the fact that you have the header files means it might be installed already. You could also try `opam depext --install pcre` to see if opam can figure out what you're missing.

**Comment by rvantonder** [comment] 2019-10-02 04:42
Found a related issue for OCaml pcre: https://github.com/mmottl/pcre-ocaml/issues/18. Perhaps one of those comments give a hint (check `pkg-config` and PATH)?

**Comment by SenorAgosto** [comment] 2019-10-05 03:34
> Found a related issue for OCaml pcre: [mmottl/pcre-ocaml#18](https://github.com/mmottl/pcre-ocaml/issues/18). Perhaps one of those comments give a hint (check `pkg-config` and PATH)?

Thanks for the link. Initially, it looked very promising. I did check, and `libpcre` is a package which does not install a `pkg-config` file, so I created one based on `libpcre2`'s file, just to be stupid. 

However, I know a missing `pkg-config` file isn't the issue because the build stops on a missing header (which actually exists). If the problem was the missing `pkg-config` it would fail trying to link. 

See `/usr/local/include` is a "well known" path on OpenBSD, it's actually searched by default for C/C++ compilers on the platform. My concern is `ocaml` doesn't know to search this directory and the build is failing before getting information from `pkg-config`.

Alas, it still fails with a missing header even after a `pkg-config` file is put in place.

**Comment by SenorAgosto** [comment] 2019-10-05 03:40
> Ah, looks like you need the `pcre` system dependency first (similar to installing the OS dependencies using `apt-get`: `sudo apt-get install libpcre3-dev` or similar). I'm not totally sure what this is for BSD, but it looks like it's `sudo pkg_add -v pcre`. Try that, and then try the `opam install` command again?

@rvantonder, for your enrichment.... `sudo` was removed from OpenBSD in 5.8 for security reasons. `sudo` was replaced by `doas`. See https://man.openbsd.org/doas for more info if you're interested. 

`sudo` continues to be available as a port or package, `doas pkg_add sudo`for those that believe it's superior or need it for administrative continuity with other Unixes.

**Comment by SenorAgosto** [comment] 2019-10-05 04:11
> $ opam install conf-libpcre
> [NOTE] Package conf-libpcre is already installed (current version is 1).

So, digging into an area I'm very unfamiliar with (and where it's very uncomfortable for this old C++ developer)... 

... the synopsis in the contents of `.opam/4.07.0/.opam-switch/packages/conf-libpcre.1/opam` say this package is a "Virtual package relying on a libpcre system installation". Meaning it will only install if it finds a system `libpcre` installed, and I can `opam install conf-libpcre` successfully. 

I'm starting to think this is probably a problem with the ocaml `pcre` module itself.

**Comment by rvantonder** [comment] 2019-10-05 20:25
I'm not sure--I'll try to reproduce on a BSD installation in the next couple of days.

**Comment by SenorAgosto** [comment] 2020-02-10 19:37
FWIW, I tried building **comby** on OpenBSD 6.6 and it seems to be failing on different dependencies now. I'm not sure whether or not this represents progress. 

[Shell v0.12.0](https://github.com/ocaml/opam-repository/issues/15741)
[hack_parallel.0.1.1](https://github.com/ocaml/opam-repository/issues/15740)

**Comment by rvantonder** [comment] 2021-05-21 10:39
I believe both dependencies now build on BSD. I'm closing this unless I'm wrong, in which case, feel free to reopen.

**Closed by rvantonder** 2021-05-21 10:39 UTC
