### ISSUE TITLE
C braces

### ISSUE THREAD

**Issue by bugadani** [comby-tools/comby#116] opened 2019-09-30 17:23 UTC
I sketched up an example that I can run on my code: bit.ly/2n0kqP8
Then I tried to apply it to this file: https://github.com/RevolutionRobotics/RevvyFirmware/blob/master/main.c

And the resulting diff is the attached image.
![image](https://user-images.githubusercontent.com/977627/65901063-ac416d00-e3b7-11e9-8ba6-bc4ff310ec8c.png)

Comby 0.9.1 was freshly installed on an Ubuntu that runs on top of WSL.

**Comment by rvantonder** [comment] 2019-09-30 18:07
Hi! I wasn't able to reproduce this. I used the pattern from your link above:

```
COMBY_M="$(cat <<"MATCH"                                                                     [14:04:15]
if (:[cond])
    :[x.]
MATCH
)"
COMBY_R="$(cat <<"REWRITE"
if (:[cond]) { :[x] }
REWRITE
)"
# Install comby with `bash <(curl -sL get.comby.dev)` or see github.com/comby-tools/comby && \
comby $COMBY_M $COMBY_R  .c -stats
```

There are zero matches:

```
{
  "number_of_files": 1,
  "lines_of_code": 163,
  "number_of_matches": 0,
  "total_time": 94.99597549438477
}
```

I also tried a simpler command (if you want to try this one to check for yourself): 

`comby 'if (:[cond]) :[x.]' 'if (:[cond]) { :[x] }' .c -stats`

It also produces no matches. Could you share your command line command (I'm wondering if it is something to do with how it's interpreted in your setup, as a guess).

**Comment by rvantonder** [comment] 2019-09-30 18:13
Update: I'm able to reproduce this in a different terminal setup, for the copied command from the live example. I'll investigate. In the meantime, the following should work:

`comby 'if (:[cond]) :[x.]' 'if (:[cond]) { :[x] }' .c -stats`

**Comment by bugadani** [comment] 2019-09-30 18:13
Thank you very much, the one-liner indeed works.

**Comment by rvantonder** [comment] 2019-09-30 18:23
Looks like the command line variables needed quotes :) Fixed in https://github.com/comby-tools/comby-ui/commit/f930ca1d969e485cce38324c841bd85ee5b879f6 and the fix is running live (I tested your example). Feel free to reopen if you still run into problems.

**Closed by rvantonder** 2019-09-30 18:23 UTC
