### ISSUE TITLE
.go doesn't limit to .go files only

### ISSUE THREAD

**Issue by junkblocker** [comby-tools/comby#184] opened 2020-05-12 19:57 UTC
**Describe the bug**
```
% comby -match-only 'if :[hole] = :[hole] { [:whatever] }' .go
```

is trying to look at non-go files also.

**Reproducing**
```
% cd /Users/foo/bar
% comby -match-only 'if :[hole] = :[hole] { [:whatever] }' .go
Timeout for input: Path: /Users/foo/bar/baz/worker.py!
...
```
and so on. Have to resort to manually specifying the files like so
```
% comby  -match-only 'if :[hole] = :[hole] { [:whatever] }' **/*.go
```
to not waste time and get the right behavior.

**Expected behavior**
It should only be looking at *.go files

**Additional context**

**Comment by rvantonder** [comment] 2020-05-12 20:14
Sorry, I'm not able to reproduce this on latest release. I created a directory structure files and different extensions, and set it up to know whether they get processed at all, and it doesn't look like they do. To help me out, could you tell me:

- the output of `comby -version`
- the OS distribution / binary (Mac, Ubunutu, etc.)
- describe a minimal directory structure that reproduces this on your machine

**Comment by junkblocker** [comment] 2020-05-12 20:37
Installed via homebrew

```
% comby -version
0.14.1

% uname -a
Redacted foo.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

% mkdir -p foo/bar/baz
% cd foo/bar/baz
% git init
% touch foo/bar/baz/abc.go
% cat /dev/random > foo/bar/baz/abc.py
^C after a few seconds
% comby -verbose -match-only 'if :[hole] = :[hole] { [:whatever] }' .go
Timeout for input: Path: /Users/manpreets/dev/tmp/comby/foo/bar/baz/abc.py!

WARNING: the GENERIC matcher was used, because a language could not be inferred from the file extension(s). The GENERIC matcher may miss matches. See '-list' to set a matcher for a specific language and to remove this warning.
```

**Comment by rvantonder** [comment] 2020-05-12 21:26
Gah! I see what's happening here. So the issue is comby can take up to three anonymous arguments:

`comby <match> <rewrite> <suffixes>`

where `suffixes` is optional. If it is omitted, all files will be processed. In the command with the issue, `.go` is interpretted as the `<rewrite>` pattern. The current way to avoid this would be to give a blank rewrite pattern: 
`comby -match-only 'if :[hole] = :[hole] { [:whatever] }' '' .go`

This isn't great for usability when using `-match-only`. One solution might be to add subcommands for `match` and `rewrite` that can take a different number of anonymous arguments.

**Comment by junkblocker** [comment] 2020-05-12 21:40
🤷 I'd vote for subcommands since `-match-only` screams 'no replacement pattern' but I'm not the one implementing these.

**Comment by rvantonder** [comment] 2020-05-12 22:16
:-) Happy to take feedback of course! I dislike frustrating/confusing things as much as anyone else. Originally, the `-match-only` option didn't exist, and was later tacked on. 

The other solution here is to remove the anonymous `<rewrite>` argument and put that behind an optional flag like `--rewrite`. This way, your original query would work. The potential downside is that (1) this will introduce a little inconvenience for rewriting (although arguably, this will be no more inconvenient than having to use subcommands), and (2) it would be backwards incompatible (but this is not a deal breaker). Any thoughts on that?

**Comment by junkblocker** [comment] 2020-05-12 22:39
I'm only a first time user but since you asked, I prefer 

a) syntax which has the least surprise without reading or re-reading documentation every time 
b) unambiguous specification
c) conventions in line with most of the rest of the tools out there which usually means using GNU options syntax with no subcommands, everything behind an option except filenames.

So something like the following would feel better to me

```
comby --search 'some :[thing]' --filetypes go # only search
comby --replace 'some :[thing]' 'other :[thing]' --filetypes go --filetypes py # --replace has to take two arguments
comby --replace 'some :[thing]' 'other :[thing]' **/*.go **/*.py # manually specified files
comby --replace 'some :[thing]' 'other :[thing]'  # Replace in everything in scope
comby --replace 'some :[thing]' 'other :[thing]' -- **/*.go **/*.py # This is like git grep etc.
comby --count --search 'some :[thing]' --filetypes go,py
comby --search 'some :[thing]' --stdin
```

**Comment by rvantonder** [comment] 2020-05-12 23:31
Appreciate your input! I'll be taking this into account. Feel free to close the issue--I will summarize the current problems and probably document the next direction for CLI options in a separate issue.

**Closed** 2020-05-13 01:31 UTC
